services:
  postgres:
    image: postgres:latest
    container_name: driver-postgres
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
     - "5432:5433"

  redis:
    image: redis:latest
    container_name: driver-redis
    env_file:
      - path: .env
        required: true
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - ./.docker/db:/var/lib/redis/data/
    ports:
     - "6380:6380"
