services:
  postgres:
    image: postgres:latest
    container_name: trip-postgres
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
     - "5434:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: trip-rabbit
    env_file:
      - path: .env
        required: true
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    volumes:
      - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
