services:
  postgres:
    image: postgres:latest
    container_name: user-postgres
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/
    ports:
     - "5432:5432"
